version: 0.2

env:
  parameter-store:
    GITCRYPT_KEY: "git-crypt"

batch:
  fast-fail: true
  # build-list:
  # build-matrix:
  # build-graph:

phases:
  pre_build:
    commands:
      - "bash deploy/pre_build.sh"
  build:
    commands:
      - "bash deploy/build.sh"
artifacts:
  files:
    - server.tar.gz
    - client.tar.gz
  discard-paths: yes
