version: '3'
services:
  onboard-server:
    build: server
    restart: "unless-stopped"
    ports:
      - "5000:5000"
    networks:
      - onboard-network 
    volumes:
        - client-build:/usr/src/client/build
  onboard-client:
    build: client
    networks:
      - onboard-network 
    volumes:
        - client-build:/usr/src/client/build


networks:
  onboard-network:
    external:
      name: onboard-network
volumes: 
  client-build:
