version: '3.8'
services:
  onboard-server:
    build: server
    depends_on:
      - onboard-client
    restart: "unless-stopped"
    ports:
      - "5000:5000"
    networks:
      - onboard-network
      # - meet.jitsi
    volumes:
      - client-build:/usr/src/client/build
      - /var/lib/onboard/uploads:/usr/src/server/uploads
  onboard-client:
    build: client
    networks:
      - onboard-network 
    volumes:
      - client-build:/usr/src/client/build
  caddy:
    image: caddy:2.1.1
    restart: unless-stopped
    depends_on:
      - onboard-client
      - onboard-server
    ports:
      - "80:80"
      - "443:443"
      - "18443:18443" # jitsi http
      - "18000:18000" # jitsi https
      # - "5000:5000" # onboard server
      - "15001:15001" # wbo
    volumes:
      - ./deploy/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - /tmp/caddy/data:/data
      - /tmp/caddy/config:/config
    networks:
      - onboard-network
      - meet.jitsi

networks:
  onboard-network:
    external:
      name: server_onboard-network
  meet.jitsi:
    external:
      name: meet.jitsi
volumes: 
  client-build:
