version: '3.8'
services:
  onboard-server:
    build: server
    depends_on:
      - onboard-client
    restart: "unless-stopped"
    ports:
      - "5000:5000"
    networks:
      - onboard-network
    volumes:
      - client-build:/usr/src/client/build
  onboard-client:
    build: client
    networks:
      - onboard-network 
    volumes:
      - client-build:/usr/src/client/build
  caddy:
    image: caddy:2.1.1
    restart: unless-stopped
    depends_on:
      - onboard-client
      - onboard-server
    ports:
      - "80:80"
      - "443:443"
      - "18443:8443" # jitsi http
      - "18000:8000" # jitsi https
      # - "5000:5000" # onboard server
    volumes:
      - ./deploy/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - ./deploy/caddy/data:/data
      - ./deploy/caddy/data:/config
    networks:
      - onboard-network


networks:
  onboard-network:
    external:
      name: onboard-network
volumes: 
  client-build:
