version: '3.8'
services:
  etherpad:
    image: docker.pkg.github.com/doofenshmirtz-deco-inc/onboard/etherpad:0.6.2
    restart: unless-stopped
    #volumes:
    #  - /opt/etherpad-lite/var:/opt/etherpad-lite/var
    #  - /opt/etherpad-lite/node_modules:/opt/etherpad-lite/node_modules
    ports:
      - "9001:9001"
    environment:
      # - ADMIN_PASSWORD=ETHERPAD_PASSWORD
      - ADMIN_PASSWORD=pass
      - ETHERPAD_PLUGINS="ep_draw"
    networks:
      jitsi:
        aliases:
          - "etherpad.jitsi"
  wbo:
    image: lovasoa/wbo:latest
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./wbo/wbo-boards:/opt/app/server-data <- you might choose a different local directory to store stuff
    networks:
      jitsi:
        aliases:
          - "etherpad.jitsi"


networks:
  jitsi:
    external:
      name: meet.jitsi
    
