version: '3.8'
services:
  etherpad:
    image: docker.pkg.github.com/doofenshmirtz-deco-inc/onboard/etherpad:0.6.3
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      - ADMIN_PASSWORD=lkSLdkDK1kD(<eXi#
      - ETHERPAD_PLUGINS="ep_draw"
    networks:
      jitsi:
        aliases:
          - "etherpad.jitsi"
  wbo:
    image: lovasoa/wbo:latest
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./wbo/wbo-boards:/opt/app/server-data <- you might choose a different local directory to store stuff
    networks:
      jitsi:
        aliases:
          - "etherpad.jitsi"


networks:
  jitsi:
    external:
      name: meet.jitsi
    
