version: '3'
services:
  etherpad:
    image: docker.pkg.github.com/doofenshmirtz-deco-inc/onboard/etherpad:0.1.2
    restart: ${RESTART_POLICY}
    #volumes:
    #  - /opt/etherpad-lite/var:/opt/etherpad-lite/var
    #  - /opt/etherpad-lite/node_modules:/opt/etherpad-lite/node_modules
    ports:
      - "9001:9001"
    environment:
      # - ADMIN_PASSWORD=ETHERPAD_PASSWORD
      - ADMIN_PASSWORD=pass
      - ETHERPAD_PLUGINS="ep_whiteboard"
    networks:
      jitsi:
        aliases:
          - "etherpad.jitsi"


networks:
  jitsi:
    external:
      name: meet.jitsi
    
