# This is a basic workflow to help you get started with Actions

name: Jest and Prettier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Cache server dependencies
      uses: actions/cache@v2.1.1
      with:
        path: |
          server/node_modules
        key: server-${{ runner.os }}-${{ hashFiles('server/yarn.lock') }}
        restore-keys: |
          server-${{ runner.os }}-
          
    - name: Cache client dependencies
      uses: actions/cache@v2.1.1
      with:
        path: |
          client/node_modules
          client/home/.runner/cache/Cypress
        key: client-${{ runner.os }}-${{ hashFiles('client/yarn.lock') }}
        restore-keys: |
          client-${{ runner.os }}-

    - name: Setup github packages
      working-directory: server
      run: |
        echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > ~/.npmrc

    # Runs a single command using the runners shell
    - name: Install dependencies on server
      working-directory: server
      run: |
        yarn
        yarn db:start
        sudo docker ps
        yarn db:test:create
        yarn db:seed
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run prettier check on server
      working-directory: server
      run: |
        yarn pretty:check

     # Runs a set of commands using the runners shell
    - name: Run tests on server
      working-directory: server
      run: |
        yarn test

    - name: Start server for client tests
      working-directory: server
      run: |
        yarn start &

    - name: Install dependencies on client
      working-directory: client
      run: |
        yarn

    - name: Run prettier check on client
      working-directory: client
      run: |
        yarn pretty:check

    # - name: Run tests on client
    #  uses: cypress-io/github-action@v2
    #  with:
    #    working-directory: client
    #    start: yarn start
    #    wait-on: 'http://localhost:3000'
    #    browser: chrome
    - name: Start client for client tests
      working-directory: client
      run: |
          yarn start & wait-on http://localhost:3000

    - name: Run client tests
      working-directory: client
      run: |
          yarn cypress run

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: client/cypress/screenshots

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-videos
        path: client/cypress/videos
